version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      unocss:
        patterns:
          - "*unocss*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
